//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

using UnityEditor;
using UnityEngine;

public class QualitySettings : Editor {

	/**
	 * This code is copied from https://www.youtube.com/watch?v=rMCLWt1DuqI&feature=em-subs_digest
	 * I like the scene manipulation stuff here
	 */
	public static void ChangeQualitySettingsOnAllScenes(string suffix) {
		// ask user to save the scene
		if(!EditorApplication.SaveCurrentSceneIfUserWantsTo()) {
			return;
		}

		// save current scene so we can load it later
		string currentScene = EditorApplication.currentScene;

		// traverse all scenes in build settings
		foreach(var scene in EditorBuildSettings.scenes) {
			EditorApplication.OpenScene(scene.path);
			// ChangeQuality.SetQuality(suffix); // there's this code from the video but I don't know where it came from (it's a custom MonoBehaviour)
			EditorApplication.SaveScene();
		}

		EditorApplication.OpenScene(currentScene);
	}

}
