/// <summary>
/// AUTO-GENERATED
/// This file has been autogenerated by PopupTypeEditor.cs
/// Date Generated: 9/12/2018 9:11:55 AM
/// </summary>

using System;
using System.Collections.Generic;

namespace Sandbox.Popup
{

    public partial class PopupType
    {
    
        public static readonly PopupType Invalid = new PopupType("Invalid", 0);
        public static readonly PopupType Popup001 = new PopupType("Popup001", 1);
        public static readonly PopupType Popup002 = new PopupType("Popup002", 2);
        public static readonly PopupType Popup003 = new PopupType("Popup003", 3);
        public static readonly PopupType CustomAdPopupImage = new PopupType("CustomAdPopupImage", 4);
        public static readonly PopupType CustomAdPopupVideo = new PopupType("CustomAdPopupVideo", 5);
        public static readonly PopupType Close = new PopupType("Close", 6);
        public static readonly PopupType InsufficientGoldPopup = new PopupType("InsufficientGoldPopup", 7);
        public static readonly PopupType ConvertOnline = new PopupType("ConvertOnline", 8);
        public static readonly PopupType ConvertOffline = new PopupType("ConvertOffline", 9);
        public static readonly PopupType ConnectToFGC = new PopupType("ConnectToFGC", 10);
        public static readonly PopupType Profile = new PopupType("Profile", 11);
        public static readonly PopupType DownloadFGC = new PopupType("DownloadFGC", 12);
        public static readonly PopupType ResultsPopup = new PopupType("ResultsPopup", 13);
        public static readonly PopupType PurchaseConfirmationPopup = new PopupType("PurchaseConfirmationPopup", 14);
    
        public static readonly List<PopupType> PopupTypeList = new List<PopupType>()
        {
           Invalid,
           Popup001,
           Popup002,
           Popup003,
           CustomAdPopupImage,
           CustomAdPopupVideo,
           Close,
           InsufficientGoldPopup,
           ConvertOnline,
           ConvertOffline,
           ConnectToFGC,
           Profile,
           DownloadFGC,
           ResultsPopup,
           PurchaseConfirmationPopup,
        };

        public static readonly Dictionary<string, PopupType> PopupTypeMap = new Dictionary<string, PopupType>()
        {
           { "Invalid", Invalid },
           { "Popup001", Popup001 },
           { "Popup002", Popup002 },
           { "Popup003", Popup003 },
           { "CustomAdPopupImage", CustomAdPopupImage },
           { "CustomAdPopupVideo", CustomAdPopupVideo },
           { "Close", Close },
           { "InsufficientGoldPopup", InsufficientGoldPopup },
           { "ConvertOnline", ConvertOnline },
           { "ConvertOffline", ConvertOffline },
           { "ConnectToFGC", ConnectToFGC },
           { "Profile", Profile },
           { "DownloadFGC", DownloadFGC },
           { "ResultsPopup", ResultsPopup },
           { "PurchaseConfirmationPopup", PurchaseConfirmationPopup },
        };
    }
}
