/// <summary>
/// AUTO-GENERATED
/// This file has been autogenerated by SceneTypeEditor.cs
/// Date Generated: 8/9/2018 12:09:46 PM
/// </summary>

using System;

namespace Framework
{
    [Serializable]
    public enum EScene
    {
    
        Invalid,

        System,

        Services,

        Audio,

        Preloader,

        PopupCollection,

        Background,

        Cleaner,

        Max,

        GameRoot,

        TitleRoot,

        ShopRoot,

        ResultRoot,

        SettingsRoot,

        CoinsRoot

    }
}
