/// <summary>
/// AUTO-GENERATED
/// This file has been autogenerated by SceneTypeEditor.cs
/// Date Generated: 10/10/2018 5:00:04 PM
/// </summary>

using System;

namespace Framework
{
    [Serializable]
    public enum EScene
    {
    
        Invalid,

        System,

        Services,

        Audio,

        Preloader,

        PopupCollection,

        Background,

        Cleaner,

        Max,

        GameRoot,

        TitleRoot,

        ShopRoot,

        ResultRoot,

        SettingsRoot,

        CoinsRoot,

        FGCAutomation

    }
}
