/// <summary>
/// AUTO-GENERATED
/// This file has been autogenerated by SceneTypeEditor.cs
/// Date Generated: 7/9/2018 6:44:04 PM
/// </summary>

using System;

namespace Framework
{
    [Serializable]
    public enum EScene
    {
    
        Invalid,

        System,

        Services,

        Audio,

        Preloader,

        PopupCollection,

        Background,

        Cleaner,
        
        GameRoot,

        TitleRoot,

        ShopRoot,

        ResultRoot,

        SettingsRoot,

        CoinsRoot,
        
        Max,

    }
}
