// AUTOGENERATED: DO NOT EDIT
using System;

namespace Framework
{
	[Serializable]
	public enum ESceneDepth
	{
		Invalid = 1,
		Background = 2,
		Middleground = 3,
		Foreground = 4,
		PopUp = 7,
		Overlay = 8,
		Max = 10,
	}
}
