/// <summary>
/// AUTO-GENERATED
/// This file has been autogenerated by ButtonTypeEditor.cs
/// Date Generated: 10/10/2018 2:21:39 PM
/// </summary>

using System;
using System.Collections.Generic;

namespace Sandbox.ButtonSandbox
{

    public partial class ButtonType
    {
    
        public static readonly ButtonType Invalid = new ButtonType("Invalid", 0);
        public static readonly ButtonType Login = new ButtonType("Login", 1);
        public static readonly ButtonType LoginFacebook = new ButtonType("LoginFacebook", 2);
        public static readonly ButtonType MoreGames = new ButtonType("MoreGames", 3);
        public static readonly ButtonType Currency = new ButtonType("Currency", 4);
        public static readonly ButtonType Help = new ButtonType("Help", 5);
        public static readonly ButtonType Leaderboard = new ButtonType("Leaderboard", 6);
        public static readonly ButtonType Shop = new ButtonType("Shop", 7);
        public static readonly ButtonType Play = new ButtonType("Play", 8);
        public static readonly ButtonType Settings = new ButtonType("Settings", 9);
        public static readonly ButtonType Back = new ButtonType("Back", 10);
        public static readonly ButtonType Score = new ButtonType("Score", 11);
        public static readonly ButtonType Refresh = new ButtonType("Refresh", 12);
        public static readonly ButtonType Home = new ButtonType("Home", 13);
        public static readonly ButtonType Upload = new ButtonType("Upload", 14);
        public static readonly ButtonType Close = new ButtonType("Close", 15);
        public static readonly ButtonType Ads = new ButtonType("Ads", 16);
        public static readonly ButtonType Credits = new ButtonType("Credits", 17);
        public static readonly ButtonType Restore = new ButtonType("Restore", 18);
        public static readonly ButtonType MoreGamesItem = new ButtonType("MoreGamesItem", 19);
        public static readonly ButtonType ShopItem = new ButtonType("ShopItem", 20);
        public static readonly ButtonType CoinItem = new ButtonType("CoinItem", 21);
        public static readonly ButtonType TutorialButton = new ButtonType("TutorialButton", 22);
        public static readonly ButtonType Facebook = new ButtonType("Facebook", 23);
        public static readonly ButtonType GetSynertix = new ButtonType("GetSynertix", 24);
        public static readonly ButtonType GoToTitle = new ButtonType("GoToTitle", 25);
        public static readonly ButtonType ResetGame = new ButtonType("ResetGame", 26);
        public static readonly ButtonType GoToShop = new ButtonType("GoToShop", 27);
        public static readonly ButtonType StartGame = new ButtonType("StartGame", 28);
        public static readonly ButtonType SettingsButton = new ButtonType("SettingsButton", 29);
        public static readonly ButtonType FGC = new ButtonType("FGC", 30);
        public static readonly ButtonType DownloadFGC = new ButtonType("DownloadFGC", 31);
        public static readonly ButtonType ConnectToFGC = new ButtonType("ConnectToFGC", 32);
        public static readonly ButtonType GetSynerytix = new ButtonType("GetSynerytix", 33);
        public static readonly ButtonType ConvertSynertix = new ButtonType("ConvertSynertix", 34);
        public static readonly ButtonType ClaimStamps = new ButtonType("ClaimStamps", 35);
    
        public static readonly List<ButtonType> ButtonTypeList = new List<ButtonType>()
        {
           Invalid,
           Login,
           LoginFacebook,
           MoreGames,
           Currency,
           Help,
           Leaderboard,
           Shop,
           Play,
           Settings,
           Back,
           Score,
           Refresh,
           Home,
           Upload,
           Close,
           Ads,
           Credits,
           Restore,
           MoreGamesItem,
           ShopItem,
           CoinItem,
           TutorialButton,
           Facebook,
           GetSynertix,
           GoToTitle,
           ResetGame,
           GoToShop,
           StartGame,
           SettingsButton,
           FGC,
           DownloadFGC,
           ConnectToFGC,
           GetSynerytix,
           ConvertSynertix,
           ClaimStamps,
        };

        public static readonly Dictionary<string, ButtonType> ButtonTypeMap = new Dictionary<string, ButtonType>()
        {
           { "Invalid", Invalid },
           { "Login", Login },
           { "LoginFacebook", LoginFacebook },
           { "MoreGames", MoreGames },
           { "Currency", Currency },
           { "Help", Help },
           { "Leaderboard", Leaderboard },
           { "Shop", Shop },
           { "Play", Play },
           { "Settings", Settings },
           { "Back", Back },
           { "Score", Score },
           { "Refresh", Refresh },
           { "Home", Home },
           { "Upload", Upload },
           { "Close", Close },
           { "Ads", Ads },
           { "Credits", Credits },
           { "Restore", Restore },
           { "MoreGamesItem", MoreGamesItem },
           { "ShopItem", ShopItem },
           { "CoinItem", CoinItem },
           { "TutorialButton", TutorialButton },
           { "Facebook", Facebook },
           { "GetSynertix", GetSynertix },
           { "GoToTitle", GoToTitle },
           { "ResetGame", ResetGame },
           { "GoToShop", GoToShop },
           { "StartGame", StartGame },
           { "SettingsButton", SettingsButton },
           { "FGC", FGC },
           { "DownloadFGC", DownloadFGC },
           { "ConnectToFGC", ConnectToFGC },
           { "GetSynerytix", GetSynerytix },
           { "ConvertSynertix", ConvertSynertix },
           { "ClaimStamps", ClaimStamps },
        };
    }
}
