/// <summary>
/// AUTO-GENERATED
/// This file has been autogenerated by ButtonTypeEditor.cs
/// Date Generated: 9/6/2018 6:17:55 PM
/// </summary>

using System;
using System.Collections.Generic;

namespace Sandbox.ButtonSandbox
{

    public partial class ButtonType
    {

        public static readonly ButtonType Invalid = new ButtonType("Invalid", 0);
        public static readonly ButtonType Login = new ButtonType("Login", 1);
        public static readonly ButtonType LoginFacebook = new ButtonType("LoginFacebook", 2);
        public static readonly ButtonType MoreGames = new ButtonType("MoreGames", 3);
        public static readonly ButtonType Currency = new ButtonType("Currency", 4);
        public static readonly ButtonType Help = new ButtonType("Help", 5);
        public static readonly ButtonType Leaderboard = new ButtonType("Leaderboard", 6);
        public static readonly ButtonType Shop = new ButtonType("Shop", 7);
        public static readonly ButtonType Play = new ButtonType("Play", 8);
        public static readonly ButtonType Settings = new ButtonType("Settings", 9);
        public static readonly ButtonType Back = new ButtonType("Back", 10);
        public static readonly ButtonType Score = new ButtonType("Score", 11);
        public static readonly ButtonType Refresh = new ButtonType("Refresh", 12);
        public static readonly ButtonType Home = new ButtonType("Home", 13);
        public static readonly ButtonType Upload = new ButtonType("Upload", 14);
        public static readonly ButtonType Ads = new ButtonType("Ads", 15);
        public static readonly ButtonType Credits = new ButtonType("Credits", 16);
        public static readonly ButtonType Restore = new ButtonType("Restore", 17);
        public static readonly ButtonType MoreGamesItem = new ButtonType("MoreGamesItem", 18);
        public static readonly ButtonType ShopItem = new ButtonType("ShopItem", 19);
        public static readonly ButtonType CoinItem = new ButtonType("CoinItem", 20);
        public static readonly ButtonType Close = new ButtonType("Close", 21);
        public static readonly ButtonType Facebook = new ButtonType("Facebook", 22);
        public static readonly ButtonType FGC = new ButtonType("FGC", 23);
        public static readonly ButtonType DownloadFGC = new ButtonType("DownloadFGC", 24);
        public static readonly ButtonType ConnectToFGC = new ButtonType("ConnectToFGC", 25);
        public static readonly ButtonType GetSynerytix = new ButtonType("GetSynerytix", 26);
        public static readonly ButtonType ConvertSynertix = new ButtonType("ConvertSynertix", 27);
        public static readonly ButtonType GoToTitle = new ButtonType("GoToTitle", 28);
        public static readonly ButtonType ResetGame = new ButtonType("ResetGame", 29);
        public static readonly ButtonType GoToShop = new ButtonType("GoToShop", 30);
        public static readonly ButtonType StartGame = new ButtonType("StartGame", 31);
        public static readonly ButtonType SettingsButton = new ButtonType("SettingsButton", 32);
        public static readonly ButtonType TutorialButton = new ButtonType("TutorialButton", 33);
        
        public static readonly List<ButtonType> ButtonTypeList = new List<ButtonType>()
        {
            Invalid,
            Login,
            LoginFacebook,
            MoreGames,
            Currency,
            Help,
            Leaderboard,
            Shop,
            Play,
            Settings,
            Back,
            Score,
            Refresh,
            Home,
            Upload,
            Ads,
            Credits,
            Restore,
            MoreGamesItem,
            ShopItem,
            CoinItem,
            Close,
            Facebook,
            FGC,
            DownloadFGC,
            ConnectToFGC,
            GetSynerytix,
            ConvertSynertix,
            GoToTitle,
            ResetGame,
            GoToShop,
            StartGame,
            SettingsButton,
            TutorialButton,
        };

        public static readonly Dictionary<string, ButtonType> ButtonTypeMap = new Dictionary<string, ButtonType>()
        {
            { "Invalid", Invalid },
            { "Login", Login },
            { "LoginFacebook", LoginFacebook },
            { "MoreGames", MoreGames },
            { "Currency", Currency },
            { "Help", Help },
            { "Leaderboard", Leaderboard },
            { "Shop", Shop },
            { "Play", Play },
            { "Settings", Settings },
            { "Back", Back },
            { "Score", Score },
            { "Refresh", Refresh },
            { "Home", Home },
            { "Upload", Upload },
            { "Ads", Ads },
            { "Credits", Credits },
            { "Restore", Restore },
            { "MoreGamesItem", MoreGamesItem },
            { "ShopItem", ShopItem },
            { "CoinItem", CoinItem },
            { "Close", Close },
            { "Facebook", Facebook },
            { "FGC", FGC },
            { "DownloadFGC", DownloadFGC },
            { "ConnectToFGC", ConnectToFGC },
            { "GetSynerytix", GetSynerytix },
            { "ConvertSynertix", ConvertSynertix },
            { "GoToTitle", GoToTitle },
            { "ResetGame", ResetGame },
            { "GoToShop", GoToShop },
            { "StartGame", StartGame },
            { "SettingsButton", SettingsButton },
            { "TutorialButton", TutorialButton },
        };
    }
}
