//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Common.Utils {
	/**
	 * Common interface for encryption services
	 * This was also made for dependency injection in Strange
	 */
	public interface IEncryption {

		/**
		 * Encrypts the specified raw text
		 */
		string Encrypt(string rawText);

		/**
		 * Decrypts the specified encrypted text
		 */
		string Decrypt(string encrypted);

		/**
		 * Returns whether or not the specified encrypted text can be decrypted
		 */
		bool CanDecrypt(string encrypted);

		/**
		 * Tries to decrypt the encrypted string and stores the result in the out parameter
		 * This is replacement for if(CanDecrypt(raw)) {
		 *     decrypted = Decrypt(raw);
		 * }
		 * which invokes two Decrypt() calls
		 */
		bool TryDecrypt(string encrypted, out string decrypted);

	}
}
