/// <summary>
/// AUTO-GENERATED
/// This file has been autogenerated by AudioBGMEditor.cs
/// Date Generated: 9/20/2018 11:51:46 AM
/// </summary>

using System;

namespace Framework
{
    [Serializable]
    public enum BGM
    {
    
        Bgm001,

        Bgm002

    }
}
