/// <summary>
/// AUTO-GENERATED
/// This file has been autogenerated by AudioSFXEditor.cs
/// Date Generated: 9/20/2018 11:53:50 AM
/// </summary>

using System;

namespace Framework
{
    [Serializable]
    public enum SFX
    {
    
        Sfx001,

        Sfx002

    }
}
