// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

using UnityEngine;

using Common.Fsm;
using Common.Time;

namespace Common.Fsm.Action {
	public class MoveAlongDirection : FsmActionAdapter {
	
		private Transform actor;
		private Vector3 direction;
		private float velocity;
		
		private TimeReference timeReference;
		
		/**
		 * Constructor
		 */
		public MoveAlongDirection(FsmState owner, string timeReferenceName) : base(owner) {
			this.timeReference = TimeReferencePool.GetInstance().Get(timeReferenceName);
		}
		
		/**
		 * Initializer
		 */
		public void Init(Transform actor, Vector3 direction, float velocity) {
			this.actor = actor;
			this.direction = direction;
			this.velocity = velocity;
		}
		
		public override void OnEnter() {
			Assertion.Assert(!Comparison.TolerantEquals(direction.sqrMagnitude, 0)); // direction should not be zero
			
			// normalize direction
			if(!Comparison.TolerantEquals(this.direction.sqrMagnitude, 1)) {
				this.direction.Normalize();
			}
		}
		
		public override void OnUpdate() {
			Vector3 displacement = this.direction * (this.velocity * this.timeReference.DeltaTime);
			this.actor.position = this.actor.position + displacement;
		}
		
	}
}
