using Sirenix.OdinInspector;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

public class SceneEditor_v3 : ScriptableObject
{ 
    const string SCRIPT_PATH = "Assets/Framework/System/Scripts/Data/SceneTypes.cs";
    const string FILE_PATH = "FrameworkFiles/FrameworkScenes.dat";

    public List<string> SceneTypes;
    
    private void Awake()
    {
        RefreshSceneFile();
    }

    //REFRESH THE LIST BY READING THE LINES OF THE TEXT FILE
    [Button(25)]
    private void RefreshSceneFile()
    {
        SceneTypes = new List<string>(File.ReadAllLines(FILE_PATH));
    }

    /// <summary>
    /// Generates a class that contains the SceneTypes Enum
    /// </summary>
    [Button(25)]
    private void GenerateSceneEnum()
    {
        //UPDATES TEXT FILE USING THE CURRENT LIST
        if (File.Exists(FILE_PATH) == true)
        {
            using (StreamWriter outfile = new StreamWriter(FILE_PATH))
            {
                for (int i = 0; i < SceneTypes.Count; i++)
                {
                    outfile.WriteLine(SceneTypes[i]);

                }
            }
        }

        // delete old class
        if (File.Exists(SCRIPT_PATH))
        {
            File.Delete(SCRIPT_PATH);
        }

        if (File.Exists(SCRIPT_PATH) == false)
        {
            // do not overwrite
            using (StreamWriter outfile = new StreamWriter(SCRIPT_PATH))
            {
                outfile.WriteLine("// AUTOGENERATED: DO NOT EDIT");
                outfile.WriteLine("using System;");
                outfile.WriteLine(string.Empty);
                outfile.WriteLine("namespace Framework");
                outfile.WriteLine("{");
                outfile.WriteLine("\t[Serializable]");
                outfile.WriteLine("\tpublic enum EScene");
                outfile.WriteLine("\t{");

                for (int i = 0; i < SceneTypes.Count; i++)
                {
                    outfile.WriteLine("\t\t{0},", SceneTypes[i]);
                }

                outfile.WriteLine("\t}");
                outfile.WriteLine("}");
            }
        }

        AssetDatabase.Refresh();
    }
}
