//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

using UnityEngine;

/**
 * Contains extension or utility methods related to Quaternions
 */
public static class QuaternionUtils {

	/**
	 * Returns whether or not the two quaternions are equal
	 */
	public static bool Equals(Quaternion a, Quaternion b) {
		return Quaternion.Equals(a, b);
	}

}
