//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Common.Query {
	/**
	 * A concrete implementation of a query result.
	 */
	class ConcreteQueryResult : IMutableQueryResult {

		private object result;

		public ConcreteQueryResult() {
		}

		#region IMutableQueryResult implementation
		public void Clear() {
			this.result = null;
		}

		public void Set(object result) {
			this.result = result;
		}
		#endregion

		#region IQueryResult implementation
		public T Get<T>() {
			return (T)this.result;
		}
		#endregion

	}
}
