//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Common.Query {
	/**
	 * A query result that is mutable.
	 */
	public interface IMutableQueryResult : IQueryResult {

		/**
		 * Clears the value in the result.
		 */
		void Clear();

		/**
		 * Sets the result.
		 */
		void Set(object result);

	}
}

