//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

using UnityEngine;

namespace Common
{
    /**
	 * Contains GameObject extensions
	 */
    public static class GameObjectExtensions
    {

        /**
		 * Queries for a component
		 * Throws assertion error if component is not found
		 */
        public static T GetRequiredComponent<T>(this GameObject self) where T : Component
        {
            T component = self.GetComponent<T>();
            Assertion.AssertNotNull(component);
            return component;
        }

        /**
		 * Deactivates the GameObject
		 */
        public static void Deactivate(this GameObject self)
        {
            self.SetActive(false);
        }

        /**
		 * Activates the GameObject
		 */
        public static void Activate(this GameObject self)
        {
            self.SetActive(true);
        }

        public static List<T> ToArray<T>(this List<GameObject> self) 
            //where T : Component
        {
            List<GameObject> rawResult = self.FindAll(g => g.GetComponent<T>() != null);
            List<T> result = new List<T>(rawResult.Count);
            rawResult.ForEach(g => result.Add(g.GetComponent<T>()));

            return result;
        }

    }
}

