//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

using UnityEngine;

namespace Common {
	public static class TransformExtensions {
		
		/**
		 * Sets the Y part of the Euler angle rotation
		 */
		public static void SetEulerAngleY(this Transform transform, float angle) {
			Vector3 eulerAngles = transform.eulerAngles;
			eulerAngles.y = angle;
			transform.eulerAngles = eulerAngles;
		}

		/**
		 * Sets the Z part of Euler angle rotation
		 */
		public static void SetEulerAngleZ(this Transform transform, float angle) {
			Vector3 eulerAngles = transform.eulerAngles;
			eulerAngles.z = angle;
			transform.eulerAngles = eulerAngles;
		}

	}
}

