/// <summary>
/// AUTO-GENERATED
/// This file has been autogenerated by ButtonTypeEditor.cs
/// Date Generated: 06/09/2018 2:02:08 PM
/// </summary>

using System;

namespace Framework
{
    [Serializable]
    public enum EButton
    {
    
        Invalid,

        Popup001,

        Popup002,

        Popup003,

        Close,

        Play1Player,

        Play2Player,

        Settings,

        LocalMultiplayer,

        Host,

        JoinRoom,

        JoinRandomRoom,

        CloseRoom

    }
}
