/// <summary>
/// AUTO-GENERATED
/// This file has been autogenerated by ButtonTypeEditor.cs
/// Date Generated: 7/26/2018 6:30:56 PM
/// </summary>

using System;

namespace Framework
{
    [Serializable]
    public enum EButton
    {
    
        Invalid,

        Popup001,

        Popup002,

        Popup003,

        Close,

        SelectItem,

        GoToTitle,

        StartGame,

        GoToShop,

        ResetGame,

        TutorialButton,

        LeaderboardButton,

        SettingsButton,

        PauseButton,

        ResumeButton,

        ResultsScreen

    }
}
